### ISSUE TITLE
Add Waveshare usb monitor board

### ISSUE THREAD

**Issue by manmountain** [Evlers/Buildroot-Evlers#2]
Add support for Waveshare 3.4 Inch USB Monitor
https://www.waveshare.com/product/displays/usb-monitor/2.8inch-usb-monitor.htm?sku=26771

**Soc:**
Allwinner T113-S3

**Lcd panel:**
800x800
GX034-30MB-A1
F22C3505B-B00
F10 2246

Probably this display panel:
https://www.panelook.cn/GX034-30MB-A1-3-4-TFT-LCD-screen-800-800-300cd-m-sup2-30PINS-MIPI-Circular-LCD-detail_152023.html
3.4 "TFT LCD screen, 800*800, 300cd/m², 30PINS, MIPI, Circular LCD screen, JD9365DA

Might work with:
https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/panel/panel-jadard-jd9365da-h3.c

![PXL_20240609_182638505 MP](https://github.com/Evlers/Buildroot-Evlers/assets/512198/361d2768-728e-4184-b529-be60745acbce)
![PXL_20240609_182705412](https://github.com/Evlers/Buildroot-Evlers/assets/512198/bc389d5e-3f19-4cb2-865c-fea2d1a58aea)
![PXL_20240609_182856434](https://github.com/Evlers/Buildroot-Evlers/assets/512198/7ec2b9af-d3f2-474f-9dcd-b5ef1d298854)

**Comment by Evlers** [comment]
T113 recommends tina sdk, this is just an demo.
You are also welcome to submit a PR
Thank you~
